'use client'

import { useState, useEffect } from 'react'
import { 
  EnvelopeIcon, 
  SparklesIcon,
  CheckCircleIcon,
  ClockIcon,
  EyeIcon,
  PencilIcon
} from '@heroicons/react/24/outline'
import { ClubInfo, IntentData, Contact, EmailDraft } from '@/app/dashboard/page'

interface EmailGenerationProps {
  clubInfo: ClubInfo
  intentData: IntentData
  contacts: Contact[]
  onComplete: (data: EmailDraft[]) => void
}

export default function EmailGeneration({ 
  clubInfo, 
  intentData, 
  contacts, 
  onComplete 
}: EmailGenerationProps) {
  const [emailDrafts, setEmailDrafts] = useState<EmailDraft[]>([])
  const [isGenerating, setIsGenerating] = useState(false)
  const [generationProgress, setGenerationProgress] = useState(0)
  const [error, setError] = useState('')
  const [selectedDrafts, setSelectedDrafts] = useState<Set<string>>(new Set())

  // Mock email drafts for demonstration - in real app, these would be generated by GPT
  const mockEmailDrafts: EmailDraft[] = [
    {
      id: '1',
      contact: contacts[0],
      subject: 'Partnership Opportunity: Mental Health Design Sprint',
      body: `Hi Sarah,

I hope this email finds you well! I'm reaching out on behalf of the Mental Health Advocacy Club at our university, a student group dedicated to promoting mental wellness and creating innovative solutions for student mental health challenges.

We're organizing a Mental Health Design Sprint this semester, bringing together students, mental health professionals, and technology experts to develop innovative solutions for campus mental health. Given HealthTech Solutions' impressive work in mental health technology and your role in partnerships, I believe there's a great opportunity for collaboration.

Your company's platform for student mental health counseling aligns perfectly with our event's mission. We'd love to discuss how HealthTech Solutions could support this initiative, whether through sponsorship, mentorship, or participation in the design sprint.

The event will provide excellent exposure to talented students passionate about mental health technology, and we'd be happy to highlight your company's contributions throughout the process.

Would you be interested in scheduling a brief call to discuss this opportunity further? I'd be happy to share more details about our event and explore ways we could work together.

Thank you for your time, and I look forward to hearing from you!

Best regards,
[Your Name]
Mental Health Advocacy Club`,
      status: 'draft'
    },
    {
      id: '2',
      contact: contacts[1],
      subject: 'Community Partnership: Mental Health Design Sprint',
      body: `Hi Michael,

I hope you're having a great day! I'm writing from the Mental Health Advocacy Club at our university, where we're passionate about building stronger mental health support systems for students.

We're excited to announce our upcoming Mental Health Design Sprint, an event that brings together students, mental health professionals, and community leaders to create innovative solutions for campus mental health challenges. Given your role as Community Lead at HealthTech Solutions, I believe this presents a fantastic opportunity for collaboration.

Your company's commitment to student mental health technology and community engagement makes you an ideal partner for this initiative. We'd love to explore how HealthTech Solutions could support our event, whether through community outreach, student engagement, or sponsorship opportunities.

This event will not only benefit students but also provide valuable insights into the mental health needs of young adults, which could inform your product development and community initiatives.

Would you be interested in learning more about our event and discussing potential partnership opportunities? I'd be happy to schedule a call to share more details.

Thank you for considering this opportunity!

Best regards,
[Your Name]
Mental Health Advocacy Club`,
      status: 'draft'
    },
    {
      id: '3',
      contact: contacts[2],
      subject: 'Marketing Partnership: Mental Health Innovation Event',
      body: `Hi Emily,

I hope this email finds you well! I'm reaching out from the Mental Health Advocacy Club at our university, where we're organizing an exciting Mental Health Design Sprint this semester.

This event will bring together students, mental health professionals, and technology experts to develop innovative solutions for campus mental health challenges. Given MindfulAI's leadership in AI-powered mental wellness and your role in marketing, I believe there's a compelling opportunity for collaboration.

Your company's innovative approach to personalized meditation and stress management aligns perfectly with our event's focus on technology-driven mental health solutions. We'd love to explore how MindfulAI could support this initiative, whether through sponsorship, product demonstrations, or participation in the design sprint.

This partnership would provide excellent exposure to students passionate about mental health technology and could help showcase MindfulAI's innovative solutions to a highly engaged audience.

Would you be interested in discussing this opportunity further? I'd be happy to schedule a call to share more details about our event and explore ways we could work together.

Thank you for your time!

Best regards,
[Your Name]
Mental Health Advocacy Club`,
      status: 'draft'
    }
  ]

  const generateEmails = async () => {
    setIsGenerating(true)
    setError('')
    setGenerationProgress(0)

    try {
      // Simulate API call with progress updates
      const progressInterval = setInterval(() => {
        setGenerationProgress(prev => {
          if (prev >= 100) {
            clearInterval(progressInterval)
            return 100
          }
          return prev + 20
        })
      }, 400)

      // Simulate API delay
      await new Promise(resolve => setTimeout(resolve, 4000))
      
      clearInterval(progressInterval)
      setGenerationProgress(100)
      
      // In real app, this would call the Python backend with GPT
      // const response = await fetch('/api/python/generate-emails', {
      //   method: 'POST',
      //   headers: { 'Content-Type': 'application/json' },
      //   body: JSON.stringify({ clubInfo, intentData, contacts })
      // })
      
      // For now, use mock data
      setEmailDrafts(mockEmailDrafts)
      
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to generate emails')
    } finally {
      setIsGenerating(false)
    }
  }

  const toggleDraftSelection = (draftId: string) => {
    const newSelected = new Set(selectedDrafts)
    if (newSelected.has(draftId)) {
      newSelected.delete(draftId)
    } else {
      newSelected.add(draftId)
    }
    setSelectedDrafts(newSelected)
  }

  const handleContinue = () => {
    const selected = emailDrafts.filter(draft => selectedDrafts.has(draft.id))
    onComplete(selected)
  }

  const previewEmail = (draft: EmailDraft) => {
    // In a real app, this would open a modal or expand the email content
    console.log('Preview email:', draft)
  }

  const editEmail = (draft: EmailDraft) => {
    // In a real app, this would open an edit form
    console.log('Edit email:', draft)
  }

  useEffect(() => {
    // Auto-start generation when component mounts
    generateEmails()
  }, [])

  return (
    <div className="space-y-6">
      <div className="text-center">
        <h2 className="text-2xl font-bold text-gray-900 mb-2">Generate Personalized Emails</h2>
        <p className="text-gray-600">
          Our AI will create tailored outreach emails for each contact, personalized to their role and company.
        </p>
      </div>

      {/* Summary Information */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className="p-4 bg-blue-50 border border-blue-200 rounded-lg">
          <h3 className="font-medium text-blue-900 mb-1">Club</h3>
          <p className="text-blue-800 text-sm">{clubInfo.summary.substring(0, 100)}...</p>
        </div>
        <div className="p-4 bg-green-50 border border-green-200 rounded-lg">
          <h3 className="font-medium text-green-900 mb-1">Request</h3>
          <p className="text-green-800 text-sm">{intentData.description.substring(0, 100)}...</p>
        </div>
        <div className="p-4 bg-purple-50 border border-purple-200 rounded-lg">
          <h3 className="font-medium text-purple-900 mb-1">Contacts</h3>
          <p className="text-purple-800 text-sm">{contacts.length} contacts selected</p>
        </div>
      </div>

      {/* Generation Progress */}
      {isGenerating && (
        <div className="p-4 bg-yellow-50 border border-yellow-200 rounded-lg">
          <div className="flex items-center space-x-2 mb-3">
            <ClockIcon className="h-5 w-5 text-yellow-600" />
            <span className="font-medium text-yellow-800">Generating Emails...</span>
          </div>
          <div className="w-full bg-yellow-200 rounded-full h-2">
            <div 
              className="bg-yellow-600 h-2 rounded-full transition-all duration-300"
              style={{ width: `${generationProgress}%` }}
            ></div>
          </div>
          <p className="text-yellow-700 text-sm mt-2">
            AI is crafting personalized emails using GPT-4...
          </p>
        </div>
      )}

      {/* Error Display */}
      {error && (
        <div className="p-4 bg-red-50 border border-red-200 rounded-lg">
          <p className="text-red-800">{error}</p>
          <button
            onClick={generateEmails}
            className="mt-2 btn-primary text-sm"
          >
            Try Again
          </button>
        </div>
      )}

      {/* Email Drafts */}
      {emailDrafts.length > 0 && (
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <h3 className="text-lg font-medium text-gray-900">
              Generated {emailDrafts.length} Email Drafts
            </h3>
            <div className="text-sm text-gray-600">
              {selectedDrafts.size} of {emailDrafts.length} selected
            </div>
          </div>

          <div className="space-y-4">
            {emailDrafts.map((draft) => (
              <div
                key={draft.id}
                className={`border rounded-lg overflow-hidden transition-all duration-200 ${
                  selectedDrafts.has(draft.id)
                    ? 'border-primary-500 bg-primary-50'
                    : 'border-gray-200 hover:border-gray-300'
                }`}
              >
                <div className="p-4">
                  <div className="flex items-start space-x-3">
                    <input
                      type="checkbox"
                      checked={selectedDrafts.has(draft.id)}
                      onChange={() => toggleDraftSelection(draft.id)}
                      className="mt-1 h-4 w-4 text-primary-600 border-gray-300 rounded focus:ring-primary-500"
                    />
                    
                    <div className="flex-1">
                      <div className="flex items-center justify-between mb-3">
                        <div>
                          <h4 className="font-semibold text-gray-900">{draft.contact.name}</h4>
                          <p className="text-sm text-gray-600">{draft.contact.title} at {draft.contact.companyName}</p>
                        </div>
                        <div className="flex items-center space-x-2">
                          <button
                            onClick={() => previewEmail(draft)}
                            className="p-2 text-gray-400 hover:text-gray-600 transition-colors duration-200"
                            title="Preview email"
                          >
                            <EyeIcon className="h-4 w-4" />
                          </button>
                          <button
                            onClick={() => editEmail(draft)}
                            className="p-2 text-gray-400 hover:text-gray-600 transition-colors duration-200"
                            title="Edit email"
                          >
                            <PencilIcon className="h-4 w-4" />
                          </button>
                        </div>
                      </div>
                      
                      <div className="mb-3">
                        <h5 className="font-medium text-gray-900 mb-1">Subject:</h5>
                        <p className="text-gray-700 text-sm">{draft.subject}</p>
                      </div>
                      
                      <div>
                        <h5 className="font-medium text-gray-900 mb-1">Email Preview:</h5>
                        <div className="bg-gray-50 p-3 rounded border text-sm text-gray-700 max-h-32 overflow-hidden">
                          {draft.body.substring(0, 200)}...
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Action Buttons */}
      <div className="flex justify-center space-x-4">
        {emailDrafts.length === 0 && !isGenerating && (
          <button
            onClick={generateEmails}
            className="btn-primary flex items-center space-x-2"
          >
            <SparklesIcon className="h-5 w-5" />
            <span>Generate Emails</span>
          </button>
        )}
        
        {emailDrafts.length > 0 && selectedDrafts.size > 0 && (
          <button
            onClick={handleContinue}
            className="btn-primary"
          >
            Continue with {selectedDrafts.size} Emails
          </button>
        )}
      </div>

      {/* Instructions */}
      {emailDrafts.length > 0 && (
        <div className="text-center text-sm text-gray-600">
          <p>Review the generated email drafts and select the ones you'd like to proceed with.</p>
          <p className="mt-1">You can preview, edit, or regenerate emails as needed before sending.</p>
        </div>
      )}
    </div>
  )
}



